# Slicing

In [1]:
import numpy as np

a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
a[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [10]:
s = slice(2, 9, 2)
a[s]

array([2, 4, 6, 8])

# Iterating Over Array

In [14]:
a = np.arange(0, 45, 5)
a = a.reshape(3, 3)
a

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [15]:
for x in np.nditer(a):
    print(x)

0
5
10
15
20
25
30
35
40


# Iteration order( c-style and f-style)

In [18]:
print(a)
for x in np.nditer(a, order="C"):
    print(x)
print()
for x in np.nditer(a, order="F"):
    print(x)

[[ 0  5 10]
 [15 20 25]
 [30 35 40]]
0
5
10
15
20
25
30
35
40

0
15
30
5
20
35
10
25
40


# Joining arrays

In [26]:
a = np.array([[1, 2], [3, 4]])
print("first array")
print(a)

b = np.array([[5, 6], [7, 8]])
print("second array")
print(b)

print()
print("Joining the two arrays along axis 0: ")
print(np.concatenate((a, b)))

print()
print("Joining the two arrays along axis 1: ")
print(np.concatenate((a, b), axis=1))

first array
[[1 2]
 [3 4]]
second array
[[5 6]
 [7 8]]

Joining the two arrays along axis 0: 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Joining the two arrays along axis 1: 
[[1 2 5 6]
 [3 4 7 8]]
