# Array Manipulation

# Array manipulation - changing shape

In [6]:
# Array manipulation - changing shape
import numpy as np

a = np.arange(9)
print("The original array:")
print(a)
print()

b = a.reshape(3, 3)
print("The modified array:")
print(b)

The original array:
[0 1 2 3 4 5 6 7 8]

The modified array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
print(b.flatten())

[0 1 2 3 4 5 6 7 8]


In [12]:
b.flatten(order="F")

array([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [13]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
np.transpose(a)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [15]:
b = np.arange(8).reshape(2, 4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
c = b.reshape(2, 2, 2)
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [24]:
np.rollaxis(c, 1, 2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [25]:
np.swapaxes(c, 1, 2)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

# Numpy Arithematic operations

In [26]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
b = np.array([10, 10, 10])
b

array([10, 10, 10])

In [28]:
np.add(a, b)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [29]:
np.subtract(a, b)

array([[-10,  -9,  -8],
       [ -7,  -6,  -5],
       [ -4,  -3,  -2]])

In [30]:
np.multiply(a, b)

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [31]:
np.divide(a, b)

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8]])