Basic operations

In [1]:
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [2]:
a.ndim

2

In [3]:
a.itemsize

4

In [6]:
a.shape

2

In [8]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.float64)
a.itemsize

8

In [11]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.complex128)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

Numpy arrays

In [15]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
l = range(0, 5)
l

range(0, 5)

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])