# Other useful function

In [2]:
import numpy as np

In [3]:
a = np.linspace(1, 3, 10)
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [7]:
# sum and axis
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.sum(axis=0))
print(a.sum(axis=1))

[5 7 9]
[ 6 15]


In [8]:
# square root and standart deviation

a = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sqrt(a))
print(np.std(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
1.707825127659933


In [9]:
# ravel function
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x.ravel())

[1 2 3 4 5 6]
